theme:
  colors:
    primary: "#800000" # Maroon
    secondary: "#333333"
    neutral: "#ffffff"
  pack: "default"
typography:
  families:
    heading: "Roboto"
    body: "Roboto"
    nav: "Roboto"
    code: "Roboto Mono"
